INSERT INTO items (id, name, description, price, popular, imageURL) VALUES
(1, 'Parmesan Bread Bites 16 piece', 'Sixteen oven-baked bread bites handmade from fresh buttery-tasting dough and seasoned with garlic and Parmesan.', '$10.29', TRUE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvNzFhZGE3MzU4YWE0YTJmNjA5NDRjYmNlMTg4MDRhODcvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(2, 'Large Pepperoni Pizza 14" Hand Tossed Crust', 'Traditional 14" hand tossed crust, topped with robust inspired tomato sauce, cheese made with 100% mozzarella, and pepperoni.', '$22.28', TRUE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvNThiZGM3NWJmNmM4MDdiYWMzMzgyODdlNTVjMWI5NmUvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(3, 'Medium Pepperoni Pizza 12" Hand Tossed Crust', 'Traditional 12" hand tossed crust, topped with robust inspired tomato sauce, cheese made with 100% mozzarella, and pepperoni.', '$18.68', FALSE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvNTc3YjlmNDIyMGNhMmNiMmM0ODA0ODcyNjU2MWU5YzQvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(4, 'Large Cheese Pizza 14" Hand Tossed Crust', 'Traditional 14" hand tossed crust, topped with robust inspired tomato sauce, and cheese made with 100% mozzarella.', '$19.09', FALSE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvZWI0MDAyMjVjYWQyNWM0MmQ5YzhmOTIzNjkyNTNiN2UvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(5, 'Medium Cheese Pizza 12" Hand Tossed Crust', 'Traditional 12" hand tossed crust, topped with robust inspired tomato sauce, and cheese made with 100% mozzarella.', '$15.49', FALSE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvOWRhYzUwNTgwYjg4ZjRlMzRhNzgwYmUyMzAyYWY0MmMvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(6, 'Medium Pepperoni Pizza 12" Handmade Pan Crust', 'Two layers of cheese, pepperoni topping to the edge, baked in a pan for a 12" handmade pan crust that is golden and crispy with a buttery taste.', '$21.08', FALSE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvZGZlYzg1MmY2MzdkODU1YzIyNGUzYzIyYmZiM2M1ODMvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(7, 'Large MeatZZa 14" Hand Tossed Crust', 'Traditional 14" hand tossed crust topped with pepperoni, ham, Italian sausage and beef, all sandwiched between two layers of provolone and cheese made with 100% real mozzarella.', '$26.29', FALSE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvMGFmZjdiOTM5MzcxY2FlZDUyZWVmMzk1N2ZiYjYyMzEvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(8, 'Medium Pacific Veggie Pizza 12" Crunchy Thin Crust', 'Fresh baby spinach, fresh onions, fresh mushrooms, tomatoes, black olives, feta, provolone, cheese made with 100% real mozzarella and sprinkled with a garlic herb seasoning topping a 12" crunchy thin crust.', '$22.69', FALSE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvNTI4NzQyZDM1M2ZjYTZjMGVhMDU3NzVhYTQ3NTllMGUvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(9, 'Chicken Alfredo Pasta', 'Grilled chicken breast and creamy Alfredo sauce is mixed with penne pasta and baked to creamy perfection.', '$11.89', FALSE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvZWVjNDZhOGQ2ZDY5Yjk0MDAzYjZiNTQ0YzRkMTc2ZWEvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(10, 'Stuffed Cheesy Bread', 'Our oven-baked breadsticks are generously stuffed and covered with a blend of 100% real mozzarella and cheddar cheeses then seasoned with a touch of garlic.', '$11.89', FALSE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvMDkwY2E2YTE2NmM5YTYyNTFjNWI1N2M4NjVlMjM3MjIvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(11, 'Coke 20 oz', 'A 20-ounce authentic cola sensation that is a refreshing part of sharing lifes enjoyable moments.', '$3.49', FALSE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvZWE3YmI3YTkzZTc4YmY4Yzc0OGVhNWRjYTY3MWFjZTEvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(12, 'Hot Buffalo Wings 8 piece with Ranch dip cup', 'Eight buffalo wings marinated and oven-baked, then smothered in hot buffalo sauce and paired with a ranch dipping cup.', '$14.29', FALSE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvZjI2YTJkNjJhMTU5ODJmZmY5OWYzYjc1ZTIyNDFkNzcvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw=='),
(13, 'Chocolate Lava Crunch Cakes', 'Indulge in three delectable oven-baked chocolate cakes with molten chocolate fudge on the inside. Perfectly topped with a dash of powdered sugar.', '$11.89', TRUE, 'https://cn-geo1.uber.com/image-proc/resize/eats/format=webp/width=550/height=440/quality=70/srcb64=aHR0cHM6Ly90Yi1zdGF0aWMudWJlci5jb20vcHJvZC9pbWFnZS1wcm9jL3Byb2Nlc3NlZF9pbWFnZXMvM2RkOTdjMjJkM2Q3NWQwNjA1NGMyNzY1NjJkNDVjNTEvYTE5YmIwOTY5MjMxMGRmZDQxZTQ5YTk2YzQyNGIzYTYuanBlZw==');
