(function(a){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,b=d?d("ARARegisterTrigger@utils","ARARegisterTrigger"):c;b.guardFatal?b.guardFatal(a)(b,window):b.execute(function(){a(b,window)})})(function(a,c,d){a.now("ARAConfiguration").execute(function(c){c||a.register("ARAConfiguration",function(){return{getRoboticSessionId:function(){return"000-0000000-0000000"},getUserAgent:function(){return navigator.userAgent}}})});"use strict";a.now("ARAAddMetric").execute(function(b){b||
a.register("ARAAddMetric",function(){return{addMetric:function(a,b){c.ue&&c.ue.count&&c.ue.count(a,b)}}})});"use strict";a.now("ARALogError").execute(function(b){b||a.register("ARALogError",function(){return{logError:function(a){var b={logLevel:2<arguments.length&&arguments[2]!==d?arguments[2]:"ERROR",attribution:"ARARegisterTrigger",message:1<arguments.length&&arguments[1]!==d?arguments[1]:""};c.ueLogError&&c.ueLogError(a,b);return[a,b]}}})});"use strict";a.now("ARAUtils").execute(function(b){b||
a.register("ARAUtils",function(){function a(){return c.opts}var b=/development|beta/,m=/pre-prod|gamma/,n={"Google Chrome":106};return{getWindowOpts:a,getHref:function(){return c.location.href},getStage:function(a){return b.test(a)?"beta":m.test(a)?"gamma":"prod"},getCustomerId:function(){return a().customerId},getSessionId:function(){return a().sessionId},getNavigator:function(){return navigator},registerFetch:function(a){return c.fetch(a,{keepalive:!0,attributionReporting:{eventSourceEligible:!1,
triggerEligible:!0}})},checkIsBrowserSupported:function(){var a=navigator.userAgentData;if(null==a)return!1;a=a.brands;a:{if(a&&0!==a.length){var b=!0,c=!1,g=d;try{for(var e=a[Symbol.iterator](),h;!(b=(h=e.next()).done);b=!0){var l=h.value;if(Number.parseFloat(l.version)>=n[l.brand]){var f=!0;break a}}}catch(p){c=!0,g=p}finally{try{!b&&e.return&&e.return()}finally{if(c)throw g;}}}f=!1}return f},checkIsFeatureAllowed:function(){return"featurePolicy"in document&&"function"===typeof document.featurePolicy.allowsFeature?
document.featurePolicy.allowsFeature("attribution-reporting"):!1},getDetailPageState:function(){if(c.DetailPage&&c.DetailPage.StateController)return c.DetailPage.StateController.getState()}}})});"use strict";a.now("ARARegisterTriggerHelpers").execute(function(b){b||a.when("ARAConfiguration","ARAAddMetric","ARALogError","ARAUtils").register("ARARegisterTriggerHelpers",function(a,b,c,d){function f(a){switch(a){case "beta":return"https://beta-ara.paa-reporting-advertising.amazon";case "gamma":return"https://gamma-ara.paa-reporting-advertising.amazon";
case "prod":return"https://ara.paa-reporting-advertising.amazon"}}function k(a,g,e,h){return d.registerFetch(a).then(function(c){if(g<e)return c.ok?(b.addMetric("ARA:RegisterDPVResponseRecieved",1),c.json()):new Promise(function(b,c){setTimeout(function(){k(a,g+1,e,2*h).then(b).catch(c)},h)});throw Error("Exceeded maximum retries");}).catch(function(a){b.addMetric("ARA:RegisterDPVResponseError",1);c.logError(a,"ARA:RegisterDPVResponseError. Error receiving response from ARAService")})}return{generateGatewayUrl:f,
browserSupportsARA:function(){var a=d.checkIsBrowserSupported(),c=d.checkIsFeatureAllowed();a?c||b.addMetric("ARA:ARAFeatureNotEnabled",1):b.addMetric("ARA:UserAgentNotSupported",1);return a&&c},registerTrigger:k,createQueryParams:function(a,b){b=f(b)+"/conversion?";var c={asin:a.pageInformation.asin,eventType:"dpv",debugKey:a.identity.customerId,marketId:1,requestId:a.identity.requestId},d=encodeURIComponent;a=Object.keys(c).map(function(a){return d(a)+"\x3d"+d(c[a])}).join("\x26");return b+a}}})})});
/* ******** */
(function(d){var c=window.AmazonUIPageJS||window.P,f=c._namespace||c.attributeErrors,b=f?f("ARARegisterTrigger@dpv","ARARegisterTrigger"):c;b.guardFatal?b.guardFatal(d)(b,window):b.execute(function(){d(b,window)})})(function(d,c,f){d.now("DetailedPageInfo").execute(function(b){b||(d.when("A").register("DetailedPageInfo",function(b){var a={init:function(g,b,e,c,d){a.config=g;a.helpers=c;a.utils=d;a.metrics=b;a.errors=e;a.retrieveDPV(!1)},retrieveDPV:function(b){var c=a.utils.getHref();if(c)if(a.helpers.browserSupportsARA()){a.metrics.addMetric("ARA:BrowserSupportsARA:True",
1);var e=a.utils.getWindowOpts();if(e){var d=a.utils.getDetailPageState(),f=a.utils.getStage(c),g=a.utils.getSessionId(),l=e.pageType,m=a.utils.getCustomerId(),n=e.obfuscatedMarketId,p=e.requestId,h=a.config.getRoboticSessionId();h=g===h;var k=void 0;b?d&&d.current_asin?k=d.current_asin:a.metrics.addMetric("ARA:DetailPageStateNotFound",1):k=e.asin;!h&&k?(b=a.helpers.createQueryParams({identity:{sessionId:g,customerId:m,requestId:p},pageInformation:{pageURL:c,pageType:l,asin:k,obfuscatedMarketId:n}},
f),a.helpers.registerTrigger(b,0,5,100),a.metrics.addMetric("ARA:BrowserSupportsARA:DPV",1)):a.metrics.addMetric("ARA:TotalPunts",1);h&&a.metrics.addMetric("ARA:RoboticTraffic:True",1)}else a.metrics.addMetric("ARA:OptsNotFoundError",1),b={message:"ARA:OptsNotFoundError. Error getting windowOpts."},a.errors.logError(b)}else a.metrics.addMetric("ARA:BrowserSupportsARA:False",1);else a.metrics.addMetric("ARA:PageLoadError",1),b={message:"ARA:PageLoadError. Error retrieving url from window."},a.errors.logError(b)}};
b.on("PageRefresh:ATF",function(){a.metrics?(a.metrics.addMetric("ARA:DPVTwisterEventCaptured",1),a.retrieveDPV(!0)):c.ue&&c.ue.count&&c.ue.count("ARA:DPVTwisterEventMissed",1)});return a}),d.when("ARAConfiguration","ARAAddMetric","ARALogError","ARARegisterTriggerHelpers","ARAUtils","DetailedPageInfo","ready").execute(function(b,a,c,d,e,f){f.init(b,a,c,d,e)}))})});
/* ******** */
