'use strict';mix_d("CerberusSharedCards__cerberus-shared:cerberus-shared__GolD59HI","require exports tslib @p/A @c/metrics @c/aui-truncate @c/aui-utils @c/logger @c/pagemarker @c/remote-operations @c/scoped-dom @c/tracking @c/aui-feature-detect".split(" "),function(W,X,q,ba,R,ca,da,r,ea,fa,ha,S,ia){function F(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function Y(a){if(a&&a.__esModule)return a;var d=Object.create(null);a&&Object.keys(a).forEach(function(b){if("default"!==b){var c=
Object.getOwnPropertyDescriptor(a,b);Object.defineProperty(d,b,c.get?c:{enumerable:!0,get:function(){return a[b]}})}});d["default"]=a;return d}var C=F(ba),n=F(R),ja=F(ca),ka=F(da),la=F(ea),ma=F(fa),T=F(ha),na=F(ia),Z={},U=function(a,d,b){void 0===d&&(d="");void 0===b&&(b=1);d=a+d;Z.hasOwnProperty(d)||(Z[d]=!0,R.count(a,(R.count(a)||0)+b))},oa=function(a){U(C["default"].capabilities.mobile?"Card:EERU:SharedLib:mobile:render":"Card:EERU:SharedLib:desktop:render");var d=function(c,e){c={$event:{preventDefault:C["default"].$.noop,
stopPropagation:C["default"].$.noop},$target:c.getContent().find('[data-a-tab-name="'+e+'"]'),data:{name:"energyEfficiencyTabSet"}};C["default"].trigger("a:declarative:a-tabs:click",c)},b=function(c,e){var f=c&&c.$event,g=c&&c.data||{},w=g.activeTabName,x=g.modalHeight,m=g.name;f&&f.preventDefault&&f.preventDefault();f&&f.stopPropagation&&f.stopPropagation();f=e.get(m);f||(C["default"].on("a:popover:beforeShow:"+m,function(h){h.popover&&h.popover.getContent&&(h=h.popover.getContent(),h.find(".a-manually-loaded").parent().css("min-height",
x),C["default"].loadDescendantImagesManually(h))}),f=e.create(c.$target,g));f.show();d(f,w)};a.when("a-secondary-view").execute("RegisterEnergyEfficiencyEventMobile",function(c){C["default"].declarative("card-energy-efficiency-secondary-view","click",function(e){U("Card:EERU:SharedLib:mobile:click",e&&e.data&&e.data.name||"");b(e,c)})});a.when("a-modal").execute("RegisterEnergyEfficiencyEventDesktop",function(c){C["default"].declarative("card-energy-efficiency-modal","click",function(e){U("Card:EERU:SharedLib:desktop:click",
e&&e.data&&e.data.name||"");b(e,c)})})},pa=function(a){a.when("ready").execute("EEBadgeProductFicheResize",function(d){var b=C["default"].$;b(".energyEfficiencyContainer").each(function(c,e){c=b(e).find(".energyEfficiencyProductFicheLabel").first();e=b(e).find("svg").first();c.parent().outerHeight()>e.outerHeight()&&(c.removeClass("a-size-small"),c.addClass("a-size-micro"),c.parent().outerHeight()>e.outerHeight()&&c.parent().css("line-height","10px"))})})},qa=function(){var a=window.P;oa(a);pa(a)},
P={wb:1},ra=function(a){return{subsAsin:a.asin,subsAvgRating:a.reviewRating,subsCurrency:a.currencyCode,subsHighestPrice:parseFloat(a.priceRangeHigh||"")||void 0,subsIsParent:a.isParent,subsIsPrime:a.isPrime,subsIsPrimeBadgeLazy:a.isPrimeBadgeLazyEnabled,subsLowestPrice:parseFloat(a.priceRangeLow||"")||void 0,subsPosition:a.position-1,subsPrice:parseFloat(a.price||"")||0,subsPrimeEligible:a.isPrime,subsSourcesMap:a.substituteSourcesMap,subsTotalReviews:a.reviewCount,subsSource:null,subsSourceScore:null}},
sa=function(a){return q.__awaiter(void 0,void 0,void 0,function(){var d,b;return q.__generator(this,function(c){switch(c.label){case 0:return na["default"].isSupported("isAmazonApp")?[4,new Promise(function(e,f){W(["@m/mash"],function(g){e(Y(g))},f)})]:[3,2];case 1:return d=c.sent(),d.cart.didUpdate({newCartQuantity:a}),[3,4];case 2:return[4,new Promise(function(e,f){W(["@p/nav.setCartCount"],function(g){e(Y(g))},f)})];case 3:b=c.sent(),b.default(a),c.label=4;case 4:return[2]}})})},V=function(a,d,
b,c){var e="none",f="none",g="none";"undefined"===typeof c?e="block":c?f="block":g="block";a&&(a.style.display=e);d&&(d.style.display=f);b&&(b.style.display=g)},ta=function(a){if("object"!==typeof a||!a)throw Error("ASIN faceout element is not valid");a=a.dataset;return{asin:a.asin||"",currencyCode:a.currencycode||"",hasPriceRange:"true"===a.haspricerange,isMapSuppressed:"true"===a.ismapsuppressed,isParent:"true"===a.isparent,isPrime:"true"===a.isprime,isPrimeBadgeLazyEnabled:"true"===a.isprimebadgelazyenabled,
offerListingId:a.offerlistingid,position:Number(a.position)||-1,price:a.price||"",priceRangeHigh:a.pricerangehigh,priceRangeLow:a.pricerangelow,reviewCount:Number(a.reviewcount)||0,reviewRating:parseFloat(a.reviewrating||"")||0,substituteSourcesMap:a.substitutesourcesmap}},ua=function(a){if("object"!==typeof a||!a)throw Error("Widget data element is not valid");a=a.dataset;var d=a.requestid,b=a.widgettype,c=a.widgettypevariant;if(!b||!d)throw Error("Required data attributes not found");return{customerId:a.customerid,
deviceType:a.devicetype||"",displayReason:a.displayreason||"",isLazyPrimeBadgeEnabled:"true"===a.islazyprimebadgeenabled,marketplaceId:a.marketplaceid||"",pageAsin:a.pageasin,producerId:a.producerid,reftag:a.reftag||"",requestId:d,sessionId:a.sessionid||"",widgetType:b,widgetTypeVariant:c||"None"}},va=function(a,d,b){b={cssGlobalClassName:"cerberusSharedCards-widgetTypeUnknown",isCart:!1,isCnsw:!1,isCompatibleProducts:!1,isCoos:!1,isFlex:!1,isFod:!1,isGemini:!1,isLpo:!1,isLpoFreeSearchVariant:!1,
isLpoShoppingAdsVariant:!1,isOos:!1,isOosGlanceViewVariant:!1,isTempOos:!1,isTempOosGlanceViewVariant:!1,isUnknown:!1,origDisplayReason:b,type:a||"Unknown",typeVariant:"None"};"Cart"===a?(b.cssGlobalClassName="cerberusSharedCards-widgetTypeCart",b.isCart=!0):"Cnsw"===a?(b.cssGlobalClassName="cerberusSharedCards-widgetTypeCnsw",b.isCnsw=!0):"CompatibleProducts"===a?(b.cssGlobalClassName="cerberusSharedCards-widgetTypeCompatibleProducts",b.isCompatibleProducts=!0):"Coos"===a?(b.cssGlobalClassName="cerberusSharedCards-widgetTypeCoos",
b.isCoos=!0):"Flex"===a?(b.cssGlobalClassName="cerberusSharedCards-widgetTypeFlex",b.isFlex=!0):"Fod"===a?(b.cssGlobalClassName="cerberusSharedCards-widgetTypeFod",b.isFod=!0):"Gemini"===a?(b.cssGlobalClassName="cerberusSharedCards-widgetTypeGemini",b.isGemini=!0):"Lpo"===a?(b.cssGlobalClassName="cerberusSharedCards-widgetTypeLpo",b.isLpo=!0,"LpoFreeSearch"===d?(b.isLpoFreeSearchVariant=!0,b.typeVariant=d):"LpoShoppingAds"===d&&(b.isLpoShoppingAdsVariant=!0,b.typeVariant=d)):"Oos"===a?(b.cssGlobalClassName=
"cerberusSharedCards-widgetTypeOos",b.isOos=!0,"OosGlanceView"===d&&(b.isOosGlanceViewVariant=!0,b.typeVariant=d)):"TempOos"===a?(b.cssGlobalClassName="cerberusSharedCards-widgetTypeTempOos",b.isTempOos=!0,"TempOosGlanceView"===d&&(b.isTempOosGlanceViewVariant=!0,b.typeVariant=d)):(b.cssGlobalClassName="cerberusSharedCards-widgetTypeUnknown",b.isUnknown=!0,b.type="Unknown");return b},wa=function(a,d,b){var c,e=b.producerId;if(e){var f=b.customerId||null,g=b.marketplaceId,w=b.sessionId,x=b.requestId,
m={deviceType:b.deviceType,seedAsin:b.pageAsin,subsReason:b.displayReason};d=function(l){var A=l.imageLinkElement,y=l.titleLinkElement,u=ra(l.dataAttributes);u=q.__assign(q.__assign({customerId:f,obfuscatedMarketplaceId:g,sessionId:w},m),u);n["default"].event(u,e,"prservices.SurfacedSubstituteEvent.6");var G=q.__assign({customerId:f,obfuscatedMarketplaceId:g,sessionId:w,subsAsin:l.asin,surfacedAsinRequestId:x},m);y?y.addEventListener("click",function(){n["default"].event(G,e,"prservices.ClickedSubstituteEvent.4")}):
r.log("CerberusSharedCards.MissingElement.titleLink not found; asin: "+l.asin,"ERROR");A?A.addEventListener("click",function(){n["default"].event(G,e,"prservices.ClickedSubstituteEvent.4")}):r.log("CerberusSharedCards.MissingElement.imageLink not found; asin: "+l.asin,"ERROR")};try{for(var h=q.__values(a),t=h.next();!t.done;t=h.next())d(t.value)}catch(l){var z={error:l}}finally{try{t&&!t.done&&(c=h.return)&&c.call(h)}finally{if(z)throw z.error;}}}else d.isCart||d.isLpo||r.log("CerberusSharedCards.NexusLogging.producerId not found",
"WARN")},xa=function(a,d,b,c,e){var f,g,w=d.reftag;if((b.isCart||b.isCompatibleProducts)&&a.length){var x=!1;try{for(var m=q.__values(a),h=m.next();!h.done;h=m.next()){var t=h.value;if(t.cartActionContainerElement){x=!0;break}}}catch(k){var z={error:k}}finally{try{h&&!h.done&&(f=m.return)&&f.call(m)}finally{if(z)throw z.error;}}if(x){var l=b.isCart?"rsi.cart.":"rsi.oos.";n["default"].count(""+l+"atc.shown."+c,1);var A=-1;b=function(k){A++;var B=k.asin,J=k.dataAttributes.offerListingId;k=k.cartActionContainerElement;
if(!k)return r.log("CerberusSharedCards.ATC.Cart action container not found; asin: "+B+"; pageAsin: "+d.pageAsin,"ERROR"),"continue";var Q=w+"_oos_atcajx_"+c+"_"+A,aa=w+"_oos_cartajx_"+c+"_"+A,p=k.querySelector("button");if(!p)return r.log("CerberusSharedCards.FindATCButton.Does not exist; asin: "+B+"; pageAsin: "+d.pageAsin,"ERROR"),{value:void 0};if(!B||!J)return r.log("CerberusSharedCards.ATC.No offer listing ID to add to cart; asin: "+B+"; pageAsin: "+d.pageAsin),p.style.visibility="hidden","continue";
var D=k.querySelector("._cerberus-shared_asinFaceoutCartAction_afCartActionMessageLoading__NgVU3"),H=k.querySelector("._cerberus-shared_asinFaceoutCartAction_afCartActionMessageSuccess__1Kidz"),E=k.querySelector("._cerberus-shared_asinFaceoutCartAction_afCartActionMessageFail__2tBPW");p.addEventListener("click",function(){return q.__awaiter(void 0,void 0,void 0,function(){var K,L,M,N,O;return q.__generator(this,function(v){switch(v.label){case 0:n["default"].count(""+l+"atc.click."+c,1),V(D,H,E,void 0),
v.label=1;case 1:return v.trys.push([1,3,,4]),K={asin:B,offerListingId:J},[4,S.addTracking(e.addToCart,{},Q||"")(K)];case 2:return v.sent(),[3,4];case 3:return L=v.sent(),r.log("CerberusSharedCards.ATC."+L.toString()+"; asin: "+B,"ERROR"),n["default"].count(""+l+"atc.fail."+c,1),V(D,H,E,!1),[2];case 4:n["default"].count(""+l+"atc.success."+c,1),M=null,v.label=5;case 5:return v.trys.push([5,7,,8]),[4,S.addTracking(e.getCartCount,{},aa||"")()];case 6:return M=v.sent(),[3,8];case 7:return N=v.sent(),
r.log("CerberusSharedCards.getCartCount."+N.toString()+"; asin: "+B,"ERROR"),n["default"].count(""+l+"gcc.fail."+c,1),[2];case 8:return n["default"].count(""+l+"gcc.success."+c,1),V(D,H,E,!0),[4,sa(M.items)];case 9:return v.sent(),O=T["default"].cardRoot.getElementsByClassName("_cerberus-shared_identifiers_idAddToCartClickedFlag__rhlYt"),0<O.length&&O[0].setAttribute("value","true"),[2]}})})})};try{for(var y=q.__values(a),u=y.next();!u.done;u=y.next()){t=u.value;var G=b(t);if("object"===typeof G)return G.value}}catch(k){var I=
{error:k}}finally{try{u&&!u.done&&(g=y.return)&&g.call(y)}finally{if(I)throw I.error;}}}else r.log("CerberusSharedCards.ATC.No cart action containers found for cart widget when items shown; pageAsin: "+d.pageAsin,"ERROR")}};X._operationNames=["addToCart","getCartCount","getPrimeBadge"];X.card=function(){return q.__awaiter(void 0,void 0,void 0,function(){var a,d,b,c,e,f,g,w,x,m,h,t,z,l,A,y,u,G,I,k,B,J,Q;return q.__generator(this,function(aa){n["default"].uet("bb","cerberus-shared",P);a=ma["default"].setup();
try{d=ua(T["default"].cardRoot.getElementsByClassName("_cerberus-shared_identifiers_idWidgetData__13wSW")[0])}catch(p){throw r.log("CerberusSharedCards.WidgetData."+p.message,"ERROR"),n["default"].count("rsi.gwdata.fail",1),p;}b=d.deviceType||"unknown";c=va(d.widgetType,d.widgetTypeVariant);c.isOos?n["default"].count("prservices.ooswidget.shown."+b,1):c.isFod?n["default"].count("prservices.fodwidget.shown."+b,1):c.isCnsw?n["default"].count("prservices.cnswwidget.shown."+b,1):c.isCart&&ja["default"].refreshAutoTruncate();
e=T["default"].cardRoot.getElementsByClassName("_cerberus-shared_identifiers_idAsinFaceoutContainer__1tA-V");f=[];g=[];w=[];for(x=0;x<e.length;x++)m=e[x],h=ta(m),t=h.asin,z=m.getElementsByClassName("_cerberus-shared_identifiers_idAsinFaceoutImageLink__2gOXw")[0],l=h.isPrimeBadgeLazyEnabled?m.getElementsByClassName("_cerberus-shared_identifiers_idAsinFaceoutLazyPrimeBadge__3MnZp")[0]:void 0,A={asin:t,cartActionContainerElement:m.getElementsByClassName("_cerberus-shared_identifiers_idAsinFaceoutCartActionContainer__2iTcx")[0],
containerElement:m,dataAttributes:h,imageElement:null===z||void 0===z?void 0:z.getElementsByTagName("img")[0],imageLinkElement:z,lazyPrimeBadgeElement:l,titleLinkElement:m.getElementsByClassName("_cerberus-shared_identifiers_idAsinFaceoutTitleLink__3_7-h")[0]},f.push(A),l&&(w.push(t),g.push(A));!d.isLazyPrimeBadgeEnabled&&g.length&&r.log("CerberusSharedCards.UnexpectedState.lazyPrimeBadges found when not enabled","ERROR");xa(f,d,c,b,a);n["default"].uet("cf","cerberus-shared",P);y=function(){n["default"].uet("be",
"cerberus-shared",P);wa(f,c,d);n["default"].uex("ld","cerberus-shared",P)};0<g.length?(u=S.addTracking(a.getPrimeBadge),u(w).then(function(p){var D;try{for(var H=q.__values(g),E=H.next();!E.done;E=H.next()){var K=E.value,L=K.asin,M=K.containerElement,N=K.lazyPrimeBadgeElement;N?p[L]?(N.classList.remove("_cerberus-shared_utilities_hidden__2mxOy"),M.dataset.isPrime="true"):(N.classList.add("_cerberus-shared_utilities_hidden__2mxOy"),M.dataset.isPrime="false"):r.log("CerberusSharedCards.MissingElement.lazyPrimeBadge not found; asin: "+
L+"; isPrime: "+p[L],"ERROR")}}catch(v){var O={error:v}}finally{try{E&&!E.done&&(D=H.return)&&D.call(H)}finally{if(O)throw O.error;}}}).catch(function(p){r.log("CerberusSharedCards.getPrimeBadge failed: "+p,"ERROR")}).then(function(){return y()})):y();G=function(p){var D=p.imageElement;D?la["default"].pageLoad.then(function(){return ka["default"].loadDynamicImage(D)}):r.log("CerberusSharedCards.MissingElement.image not found; asin: "+p.asin,"ERROR")};try{for(I=q.__values(f),k=I.next();!k.done;k=I.next())B=
k.value,G(B)}catch(p){J={error:p}}finally{try{k&&!k.done&&(Q=I.return)&&Q.call(I)}finally{if(J)throw J.error;}}qa();return[2]})})}});
