"""empty message

Revision ID: 0464d9115b18
Revises: 1d2ba33c222d
Create Date: 2025-03-21 09:10:10.205844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0464d9115b18'
down_revision = '1d2ba33c222d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_reviews_per_page', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_column('number_of_reviews_per_page')

    # ### end Alembic commands ###
