"""empty message

Revision ID: 09cebea85eb3
Revises: ad50d0fec367
Create Date: 2025-03-24 23:23:36.069464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cebea85eb3'
down_revision = 'ad50d0fec367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_of_all_ids', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_column('order_of_all_ids')

    # ### end Alembic commands ###
