"""empty message

Revision ID: 0aa7910ca110
Revises: 122280c5894a
Create Date: 2024-06-19 04:34:07.497993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa7910ca110'
down_revision = '122280c5894a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_round_id_fkey', type_='foreignkey')
        batch_op.drop_column('round_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('cart_round_id_fkey', 'round', ['round_id'], ['id'])

    # ### end Alembic commands ###
