"""empty message

Revision ID: 156b60a7a5c7
Revises: 1c7f7aa0bd30
Create Date: 2024-11-18 11:39:00.067561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156b60a7a5c7'
down_revision = '1c7f7aa0bd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_order', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_column('random_order')

    # ### end Alembic commands ###
