"""empty message

Revision ID: 1c7f7aa0bd30
Revises: cf70c705acee
Create Date: 2024-11-18 11:13:08.530409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7f7aa0bd30'
down_revision = 'cf70c705acee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_order_5', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.drop_column('random_order_5')

    # ### end Alembic commands ###
