"""empty message

Revision ID: 1d2ba33c222d
Revises: 156b60a7a5c7
Create Date: 2024-11-28 00:34:47.713174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2ba33c222d'
down_revision = '156b60a7a5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_reviews_per_page', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.drop_column('number_of_reviews_per_page')

    # ### end Alembic commands ###
