"""empty message

Revision ID: 27493b5e13ac
Revises: 54f24a2234a2
Create Date: 2024-03-26 16:53:15.761872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27493b5e13ac'
down_revision = '54f24a2234a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.String(length=80), nullable=True),
    sa.Column('product_name', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('rating_dist', sa.String(length=80), nullable=True),
    sa.Column('rating_number', sa.String(length=20), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('other_reviews', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action')
    # ### end Alembic commands ###
