"""empty message

Revision ID: 320638569ad6
Revises: 0aa7910ca110
Create Date: 2024-06-19 04:34:18.057929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320638569ad6'
down_revision = '0aa7910ca110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cart_pkey')
    )
    # ### end Alembic commands ###
