"""empty message

Revision ID: 4105f1c574e7
Revises: f0791105d86a
Create Date: 2024-04-12 10:46:06.636165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4105f1c574e7'
down_revision = 'f0791105d86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('lab_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('lab_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
