"""empty message

Revision ID: 4dd7fcf00bdb
Revises: b99e3c893e1b
Create Date: 2024-03-26 17:56:51.389184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd7fcf00bdb'
down_revision = 'b99e3c893e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_reviews', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_column('number_of_reviews')

    # ### end Alembic commands ###
