"""description of migration

Revision ID: 54f24a2234a2
Revises: 
Create Date: 2024-02-29 19:03:04.203388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f24a2234a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_file_name', sa.String(length=80), nullable=False),
    sa.Column('comment_number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    # ### end Alembic commands ###
