"""empty message

Revision ID: ad50d0fec367
Revises: 0464d9115b18
Create Date: 2025-03-24 23:07:49.512045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad50d0fec367'
down_revision = '0464d9115b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_of_ids', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_column('order_of_ids')

    # ### end Alembic commands ###
