"""empty message

Revision ID: c5654009c1f7
Revises: 4105f1c574e7
Create Date: 2024-04-14 15:25:49.397630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5654009c1f7'
down_revision = '4105f1c574e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.String(length=80), nullable=False),
    sa.Column('product_1_ar', sa.String(length=255), nullable=False),
    sa.Column('product_2_ar', sa.String(length=255), nullable=False),
    sa.Column('product_3_ar', sa.String(length=255), nullable=False),
    sa.Column('product_4_ar', sa.String(length=255), nullable=False),
    sa.Column('product_1_tr', sa.String(length=255), nullable=False),
    sa.Column('product_2_tr', sa.String(length=255), nullable=False),
    sa.Column('product_3_tr', sa.String(length=255), nullable=False),
    sa.Column('product_4_tr', sa.String(length=255), nullable=False),
    sa.Column('rating_scale_product_1_2', sa.Boolean(), nullable=True),
    sa.Column('rating_scale_product_3_4', sa.Boolean(), nullable=True),
    sa.Column('volume_product_1_2', sa.Boolean(), nullable=True),
    sa.Column('volume_product_3_4', sa.Boolean(), nullable=True),
    sa.Column('number_of_reviews_product_1', sa.Integer(), nullable=True),
    sa.Column('number_of_reviews_product_2', sa.Integer(), nullable=True),
    sa.Column('number_of_reviews_product_3', sa.Integer(), nullable=True),
    sa.Column('number_of_reviews_product_4', sa.Integer(), nullable=True),
    sa.Column('overall_rating_product_1', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('overall_rating_product_2', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('overall_rating_product_3', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('overall_rating_product_4', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('star_1_per_product_1', sa.Integer(), nullable=True),
    sa.Column('star_2_per_product_1', sa.Integer(), nullable=True),
    sa.Column('star_3_per_product_1', sa.Integer(), nullable=True),
    sa.Column('star_4_per_product_1', sa.Integer(), nullable=True),
    sa.Column('star_5_per_product_1', sa.Integer(), nullable=True),
    sa.Column('star_1_per_product_2', sa.Integer(), nullable=True),
    sa.Column('star_2_per_product_2', sa.Integer(), nullable=True),
    sa.Column('star_3_per_product_2', sa.Integer(), nullable=True),
    sa.Column('star_4_per_product_2', sa.Integer(), nullable=True),
    sa.Column('star_5_per_product_2', sa.Integer(), nullable=True),
    sa.Column('star_1_per_product_3', sa.Integer(), nullable=True),
    sa.Column('star_2_per_product_3', sa.Integer(), nullable=True),
    sa.Column('star_3_per_product_3', sa.Integer(), nullable=True),
    sa.Column('star_4_per_product_3', sa.Integer(), nullable=True),
    sa.Column('star_5_per_product_3', sa.Integer(), nullable=True),
    sa.Column('star_1_per_product_4', sa.Integer(), nullable=True),
    sa.Column('star_2_per_product_4', sa.Integer(), nullable=True),
    sa.Column('star_3_per_product_4', sa.Integer(), nullable=True),
    sa.Column('star_4_per_product_4', sa.Integer(), nullable=True),
    sa.Column('star_5_per_product_4', sa.Integer(), nullable=True),
    sa.Column('price_product_1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_product_2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_product_3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_product_4', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribution')
    # ### end Alembic commands ###
