"""empty message

Revision ID: c75242924b43
Revises: cbfac0a19d74
Create Date: 2024-07-29 12:32:38.404770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75242924b43'
down_revision = 'cbfac0a19d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
