"""empty message

Revision ID: cf70c705acee
Revises: c75242924b43
Create Date: 2024-11-18 11:09:22.416604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf70c705acee'
down_revision = 'c75242924b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_order_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('random_order_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('random_order_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('random_order_4', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.drop_column('random_order_4')
        batch_op.drop_column('random_order_3')
        batch_op.drop_column('random_order_2')
        batch_op.drop_column('random_order_1')

    # ### end Alembic commands ###
